#!/usr/bin/python3

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager 
import sys
import time
import urllib
import requests

options = webdriver.ChromeOptions()
options.add_experimental_option("detach", True)
#options.add_argument(r"--user-data-dir=/home/kaclark/.config/google-chrome")
#these options should attempt to load chrome with all user data
#options.add_argument(r'--user-data-dir=')
#PATH = "/Users/yourPath/Desktop/chromedriver"
#driver = webdriver.Chrome(PATH, options=options)

driver = webdriver.Chrome(options=options, service=Service(ChromeDriverManager().install()))
driver.get(sys.argv[1])
time.sleep(2)
tweet_info = driver.find_element(By.CLASS_NAME, "css-175oi2r").text
#imgResults = driver.find_elements(By.XPATH,"//img[contains(@class,'css-9pa8cd')]")
##img_info = driver.find_element(By.CLASS_NAME, "css-9pa8cd").
print(tweet_info.split("\n"))
'''
src = []
for img in imgResults:
    src.append(img.get_attribute('src'))
for i in range(len(src)):    
    urllib.request.urlretrieve(str(src[i]),"tw_imgs/homepage_img{}.jpg".format(i))
'''
#print(driver.page_source)

